name: Build Paper

on:
  push:
    branches:
      - develop
    tags:
      - 'QSG.*'

jobs:
  build_paper:
    name: Build LaTeX
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile LaTeX
        uses: dante-ev/latex-action@master
        with:
          working_directory: Paper
          root_file: main.tex

      - name: Rename output
        run: cp Paper/main.pdf Paper/quantum_computing_for_smart_energy_optimizations_weik.pdf

      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: BachelorThesis_Weik
          path: Paper/quantum_computing_for_smart_energy_optimizations_weik.pdf

  create_release:
    name: Create Release
    if: contains(github.ref, '/tags/')
    env:
      ref: ${{ github.ref }}
    needs: build_paper
    runs-on: ubuntu_latest
    steps:
      - run: exho Create Release