name: Build Paper
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    env:
      pdf_name: bachelorthesis_weik
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile LaTeX
        uses: dante-ev/latex-action@master
        with:
          working_directory: Paper
          root_file: main.tex

      - run: mv Paper/main.pdf Paper/$pdf_name.pdf

      - name: Publish
        uses: actions/upload-artifact@v2
        with:
          name: BachelorThesis
          path: Paper/$pdf_name.pdf