name: Build Paper

on:
  push:
    branches:
      - develop
    tags:
      - 'QSG.*'

jobs:
  build_paper:
    name: Build LaTeX
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile LaTeX
        uses: dante-ev/latex-action@master
        with:
          working_directory: Paper
          root_file: main.tex

      - name: Rename output
        run: cp Paper/main.pdf quantum_computing_for_smart_energy_optimizations_weik.pdf

      - name: Zip Code
        run: |
          mv Experiments Quantum_computing_for_smart_energy_optimizations_code_weik
          zip -r quantum_computing_for_smart_energy_optimizations_code_weik.zip Quantum_computing_for_smart_energy_optimizations_code_weik

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            quantum_computing_for_smart_energy_optimizations_weik.pdf
            quantum_computing_for_smart_energy_optimizations_code_weik.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
