name: Test Python

on: [push]
#  push:
#    branches:
#      - develop

jobs:
  test_python:
    name: Python Unittests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Couenne
        run: |
          cd Experiments/Classical/COIN-OR
          ./install_couenne_precompiled.sh
          ./install_hsl.sh

      - name: Setup Anaconda
        uses: s-weigand/setup-conda@v1

      - name: Install Anaconda Environment
        run: conda env update --file Experiments/conda_environment.yml --name base

      - name: Run Unittests
        run: |
          cd Experiments
          chmod +x run_python_verification.sh
          ./run_python_verification.sh