name: Test Python

on: [push]
#  push:
#    branches:
#      - develop

jobs:
  test_python:
    name: Python Unittests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Anaconda
        uses: s-weigand/setup-conda@v1

      - name: Install Anaconda Environment
        run: conda env create -f Experiments/conda_environment.yml

      - name: Run Unittests
        run: |
          cd Experiments
          chmod +x run_python_verification.sh
          conda init bash
          conda activate opt
          ./run_python_verification.sh