name: Test Python

on:
  push:
    branches:
      - develop
      - feature/classical_experiments

jobs:
  test_python:
    name: Python Unittests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Anaconda
        uses: s-weigand/setup-conda@v1

      - name: Install Anaconda Environment
        run: conda env update --file Experiments/conda_environment.yml --name base

      - name: Run Unittests
        run: |
          cd Experiments
          chmod +x *.sh
          ./run_python_verification.sh