name: Release Paper

on: [push]
#  push:
#    tags:
#      - 'QSG.*'

jobs:
  create_release:
    name: Craete Release
    runs-on: ubuntu-latest
    steps:
      - name: Download PDF
        uses: actions/download-artifacts@v2
        with:
          name: BachelorThesis_Weik

      - run: ls

      - run: ls Paper 